[tool.black]
line-length = 120
target-version = ['py313']

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
ignore = ["E203", "W503"]
exclude = [".venv", "__pycache__", ".git", ".mypy_cache", ".pytest_cache"]

[tool.pylint]
max-line-length = 120
