[tool.black]
line-length = 120
target-version = ['py313']

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
ignore = ["E203", "W503"]
exclude = [".venv", "__pycache__", ".git", ".mypy_cache", ".pytest_cache"]

[tool.pylint]
max-line-length = 120

[tool.pytest.ini_options]
addopts = "--cov=app --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]
python_files = "test_*.py"
asyncio_mode = "auto"
